image: aronnebrivio/php:7.4-envoy

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: blog_testing
  MYSQL_ROOT_PASSWORD: root
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - preliminaries
  - test
  - deploy

preliminaries:
  stage: preliminaries
  script:
    - cp .env.ci .env
    - composer install
    - php artisan migrate

test:
  stage: test
  script:
    - vendor/bin/phpunit

deploy_production:
  stage: deploy
  script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: http://195.110.58.197
  when: on_success
  only:
    - master
