name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Run Migrations
        run: php artisan migrate
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Run PHPUnit
        run: vendor/bin/phpunit
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
