name: CI

on: push

jobs:
  phpunit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit
